### ISSUE TITLE
[FEATURE] Add Git LFS to all the kicad* containers

### ISSUE THREAD

**Issue by hpopols** [INTI-CMNB/kicad_debian#2]
Hi everybody,

I would love to see Git LFS (debian git-lfs deb package) included in all the containers.

I think it is an important addition for people like me extensively using git LFS to store "large" blobs such as 3D models and SQLite database libraries.

Thank you for this amazing work.

Xavier

**Comment by set-soft** [comment]
Hi @hpopols !

I added it to the full images. Note that I won't generate the images right now. I'll wait to accumulate other changes. 

When Debian 12.x and Blender 3.5.x are included I'll generate new images.

**Comment by hpopols** [comment]
Hi @set-soft,

Thank you for the fast response and for taking my request in consideration! For the new image, there is no rush on my side as I can install them manually after the container creation (during CI/CD).

Thank you again and have a good day
