### ISSUE TITLE
[BUG] WSL `kibot_1.6.5-1_all.deb` not found

### ISSUE THREAD

**Issue by idem-rd** [INTI-CMNB/kicad_debian#5]
When following the steps from #264 I'm running into this issue at the last step `sudo apt-get install kibot`:

`Err:1 https://set-soft.github.io/debian bullseye/main amd64 kibot all 1.6.5-1
  404  Not Found [IP: 185.199.108.153 443]
E: Failed to fetch https://set-soft.github.io/debian/pool/main/k/kibot/kibot_1.6.5-1_all.deb  404  Not Found [IP: 185.199.108.153 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

**Comment by set-soft** [comment]
Thanks for reporting, try now.

**Comment by idem-rd** [comment]
All good! Super speedy, thanks.
